[package]
name = "docli"
version = "0.1.0-alpha"
authors = ["Kevin K <kbknapp@gmail.com>"]
description = "A command line utility to managing DigitalOcean infrastructure"
license = "MIT"
repository = "https://github.com/kbknapp/docli-rs.git"
documentation = "http://kbknapp.github.io/docli-rs"
readme = "README.md"
keywords = ["do", "cli", "digitalocean", "digital", "ocean"]


[dependencies]
clap = "*"
doapi = {path = "../doapi-rs"}
#doapi = {git = "https://github.com/kbknapp/doapi-rs"}


[features]
default = ["color"]
color = ["ansi_term"]

# for building with nightly and unstable features
unstable=[]

[dependencies.ansi_term]
version = "*"
optional = true
