[package]
name = "docli"
version = "0.1.0"
authors = ["Kevin K <kbknapp@gmail.com>"]
description = "A command line interface to managing DigitalOcean infrastructure"
license = "MIT"
repository = "https://github.com/kbknapp/docli-rs.git"
documentation = "http://kbknapp.github.io/docli-rs"
readme = "README.md"

keywords = ["do", "cli", "digitalocean", "digital", "ocean"]


[dependencies.libdo]
git = "https://github.com/kbknapp/libdo-rs"

# clap includes "suggestions" and "color" default features but we don't use colored error messages
# so we remove the "color" feature, but want to keep "suggestions"
[dependencies.clap]
version = "*"
default-features = false
features = ["suggestions"]

# for building with nightly and unstable features
unstable=[]
